### ISSUE TITLE
Video Driver issue (?)

### ISSUE THREAD

**Issue by MikeSeiler** [Geektoolkit/DynaframeProIssues#12]
I'm having trouble getting a display to work which is the focus of our use case.   Its native resolution is 2160 x 3840.  This is a bit odd size, I know.  The display works fine with Windows 11.  If I switch Dynaframe from a 1080P display after boot to the target display, all I get is a semi-random jumble of exactly horizontal lines.  If I reboot, I get a black screen.   I get exactly the same results if I use a recent, stock Raspberry Pi OS image.   This suggests a HDMI driver issue.  Any ideas for a possible fix?

**Comment by Geektoolkit** [comment]
Mike of this is for commercial we have another platform we can work with you on for commercial releases under our commercial license which may work with that resolution. Otherwise this may be something to post on the raspberry pi forums to see if you can get the custom resolution working first. I'm not sure even if you do though that the pi can push this (out other platform is not pi based)

**Comment by qwksilver** [comment]
Closing as a not specifically frame issue, please contact geektoolkit, via discord if you have any futher feedback, and feel free to open new issues if you find one.
