### ISSUE TITLE
Suggestion; Video progress bar

### ISSUE THREAD

**Issue by DeeGeeBC** [Geektoolkit/DynaframeProIssues#13]
I was wondering if it's possible to toggle a progress bar for video playback duration?

Thank you

**Comment by bdlou** [comment]
I spent a bit of time researching.  We are using LibVLCSharp to play video in VLC.  So far, I cannot find any documentation that says we can show the UI.  I will keep investigating though.

**Comment by bdlou** [comment]
@DeeGeeBC Wanted to provide an update here.  I've implemented some plumbing for video controls that will be available in an upcoming alpha.  The current plan is to allow an option to control the video play/pause, skip forward/backward via keyboard control (or remote control).  The next step will be to add UI to the web page that has transport controls, as well as a progress bar.  Due to limitations of the Raspberry Pi hardware, I would not be able to show a custom UI over a video, so I'm not sure if we'll be able to address this feedback specifically.

**Comment by Geektoolkit** [comment]
@bdlou @DeeGeeBC  We have to resolve this as won't fix for now due to pi limitations. We will continue to take a look to see if we can get an overlay on top of the video, but currently our overaly system is limited to images/animated gifs. If we find a way to do overlays on videos (which I'd LOVE to figure out) then we'll revisit this.
