### ISSUE TITLE
Overlays - Timing change needed

### ISSUE THREAD

**Issue by ajw2060** [Geektoolkit/DynaframeProIssues#28]
This relates to Build 821e376.

When an overlay is used to display text on top of the image, the overlay text appears to change at the beginning of an image transition.  Therefore during the transition the text from the next image displays immediately, even though the current image will continue to display (albeit fading) for some seconds.  This would be fine if a very short transition time was used, but the standard longer transition time will show incorrect text for some time.

Maybe the new text needs to be delayed until midway through the transition, or later, or fade out and in in sync with the image transition.

**Comment by Geektoolkit** [comment]
Yeah good call. I'll see what I can do there.  We had that issue with the infobar also, either we show it 'late' or it shows way early. Maybe something where it splits the difference of the transition time and then changes will work better. I'll see what I can do there.

**Comment by ajw2060** [comment]
Joe,
One way to address this may be as follows.
- Create a setting called something like "Overlay Display Delay" and make it a percentage of the configured transition time.
- If the user sets the Overlay Display Delay to zero, then the overlay appears at the beginning of the transition (as it seems to do right now).
- If the user sets the Overlay Display Delay to 100%, then the overlay will only appear after transition completes.
- Any value between zero and 100% controls when the overlay appears.
- Setting the Overlay Display Delay to 150% with a transition time of 10000 would delay the overlay until 5 seconds after the image is fully transitioned. 
- The maximum delay would have to be constrained, possibly to the sum of Display Time + Transition Time.
- You may have to consider also when to turn off the overlay display if a delayed start in in effect.

**Comment by Geektoolkit** [comment]
Thanks, I like that design.  Right now the way overlays are done, I'll need to add that setting to the base control...that'll probably be a February thing.  For now I added half of the logic in with some hardcoded values...what it'll do for now is when a new image is loaded, the text instantly hides (this hides the change to the new image info which happens instantly).  

The text then fades in with the new image, slightly delayed so that it loads in a second after it.

One challenge is that the images are actually 2 seperate layers, but the overlays are one.   So I can't fade an overlay out and then switch it like we do images currently. This means that the 'old' overlay data has to be dealt with.

I also realized having things like the clock fade in and out is odd, so the values have to be per control. (I had an initial implmentation that faded the entire overlay window). 

I think if I combine what i have (old overlay instantly hides) with your design, and add in the user setting, it should work nicely. I'll prototype it in Feb, for now the design I have will at least solve the wierdness of seeing data that doesn't apply to the image that you can see while the image is fading.

I'll work on it more in Feb.

**Comment by Geektoolkit** [comment]
@ajw2060 I'd added some fades to overlays for March (and am tuning them for April). Does the march fade effect help with this? I may have you take a look at Aprils release and then lets discuss if that tuned version of March handles this. One thing I"ve definitely prevented is you don't see the 'next' images overlay..before the transition starts we hide it immediately, and then the next overlay fades in with the new image (using the same overlay timing)

**Comment by Geektoolkit** [comment]
Closing for now, if we need more please reopen or open a new one with a description. I made the fade an option in the April release so you can choose what fades vs. what is static
