### ISSUE TITLE
Bug | Enabling Overlays breaks render engine and web ui.

### ISSUE THREAD

**Issue by jcrowegitHu8** [Geektoolkit/DynaframeProIssues#47]
Running the May release (Build: 1f73f91, Model: Raspberry Pi 2 Model B Rev 1.1).  I wanted to start using overlays.  Just toggling it on causes the screen to stop rendering and Dynaframe web UI to stop working.

How I "fixed" it was to hard reset and if you get the timing right there is a small window where the Web UI will work for a brief period of time that I can flip the toggle back off.  Then everything works as it did.

![OverlayToggle](https://user-images.githubusercontent.com/17546577/235754712-d5ac6e5a-e6e6-47e4-86ee-91b415c85109.PNG)

**Comment by Geektoolkit** [comment]
This is a critical fix we have to do and are investigating.  The root problem is any bad setting that ends up in the settings gets loaded, and we need a 'safe mode' so that we can either allow deleting of the settings file to recreate a new one or a way to ignore it. It's on our short list to figure out.  

When the screen stops rendering, do you see the Dynaframe name in the background? That'd mean it's crashing, which is actually easier to detect and fix than a hang

**Comment by Geektoolkit** [comment]
Closing this. we added a ton of work before the Sept. release to mitigate crashes such as this.
