### ISSUE TITLE
Bug/Stability | May release crashes consistently after running for 2 days

### ISSUE THREAD

**Issue by jcrowegitHu8** [Geektoolkit/DynaframeProIssues#48]
I upgraded to May Release (1f73f91).  I'm able to get the application to crash consistently after 2 days.  Example boot time 5/12 06:00 to 5/14 18:45.  (2 days 12 hours and 45 minutes).

If you can let me know:
1)How to write the logs either to a network share or I have a graylog instance available too if that is easier.
2)What logging should I enable to help you troubleshoot this issue.

General comment:
I found that the December release was the most stable.  Since then it feels each release while adding features is not holding very steady on the stability.

Build: 1f73f91, Model: Raspberry Pi 2 Model B Rev 1.1

**Comment by Geektoolkit** [comment]
The logs are actually shared out, if you go to the open network share on the device via \\ipaddress you should see a logs directory.  The pi 2s arent something I have to test on, so there's a number of things we could be doing in the engine that are destabilizing it that we'll have to look at.

Are you using overlays at all? that's the biggest change from December, and it's likely, as implemented, not going to play well with a pi2.

The logs will be helpful because it may show us what type of file you're hitting, the size, etc. that we can work to track down.   I've caught one issue in VLC that we're hitting that I'm tracking down (my image only frames are rock solid, but my ones with videos are lasting about 2 days like you said).  

The logs as is with 'info' level should be good, because any crashes or errors will be above 'info' level, and we can then try to see at least where the crash is.  The other thing of interest may be to turn the logs off and see if it crashes...I'm starting to wonder if the log file size that we're writing to constantly is becoming an issue.

We'll get it sorted. we have a bunch of fixes in May already, and we're constantly working on perf and stability.

**Comment by jcrowegitHu8** [comment]
Looks like you are correct.

The relevant part of the logs appears to be.
```
Out of memory.
/home/pi/Dynaframe/.config/dynaframe.sh: line 130:   800 Aborted                 sudo /home/pi/Dynaframe/Dynaframe >> $log 2>&1

dynaframe.sh we are done with this window you may now hit enter to continue
```


Full Logs here:

[dynaframe-2023-05-15-15-17.log](https://github.com/Geektoolkit/DynaframeProIssues/files/11491656/dynaframe-2023-05-15-15-17.log)

However this "out of memory" doesn't make sense as the python script I have that provides telemetry about the Dynaframe did not even break 60%.
![image](https://github.com/Geektoolkit/DynaframeProIssues/assets/17546577/44cf66ea-e4a2-4607-8c45-f7efe65b905a)

Can you help to explain what's going on?  To be clear this is crashing the entire Raspbery PI box not just the Dynaframe application.

**Comment by jcrowegitHu8** [comment]
Sorry, I forgot to answer your question.

No, I'm unable to use overlays due to the bug I posted.
https://github.com/Geektoolkit/DynaframeProIssues/issues/47

**Comment by bdlou** [comment]
Can you please go into the web interface and in the "Log" section ensure "Logging Off/On" is enabled? The log you attached makes it appear that it is turned off.  Based on the mixer control logging that did get picked up, it seems like your playlist has videos in it.  Is the playlist(s) you are running just video, or a mix of video and images?  Is your device connected just to HDMI, or is there also an analog audio jack connection?  Thanks.

**Comment by jcrowegitHu8** [comment]
Hi dblou.

1)My mistake logging was off.  Here are the logs for 1 full cycle of the playlist.  
1.A)If you want I'll drop the logging down to warning for all channels and let it run till it crashes?
[dynaframe-2023-05-17-08-42.log](https://github.com/Geektoolkit/DynaframeProIssues/files/11498888/dynaframe-2023-05-17-08-42.log)




2)Here is the playlist.
![image](https://github.com/Geektoolkit/DynaframeProIssues/assets/17546577/c8758d8e-a08e-45d1-8735-33e8b61cd86c)


3)The device is only connected to the TV via HDMI.  While the Raspberry Pi 2 Model B does have a 3.5mm headphone jack it is not used.  Here is the [amazon link](https://www.amazon.com/gp/product/B008XVAVAW/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) from original purchase if that helps for any info about specs.

**Comment by bdlou** [comment]
Thank you.  For now leave the channels as is and let the logging run until the crash is encountered and then send that our way.  Thanks!

**Comment by Geektoolkit** [comment]
Just a quick note here...the team is looking into this and discussing internally. The pi2 being what it is is likely to catch us doing something incorrect with memory quicker than a pi4, so we're discussing what has changed since December and trying to figure this out.  The 'out of memory' is a new thing we're looking into.  The overlay crashes are differenet...they are typically segfault crashes due to video memory being exhausted.

This feels like a leak, but it's going to take us some time to figure out where. And like you noticed...the pi is at 60% usage but still reported out of memory...stuff like that takes us time to figure out. Please let us know what the logs say and we'll dive in and try to figure out this puzzle.  One other thing I'm curious about is if you remove videos from the playlist does it crash, or vice versa (that'd let us know if it's a video issue or not..the one frame I am having trouble with seems to be related to videos currently..)

**Comment by jcrowegitHu8** [comment]
Thanks for sharing:

My 2 cents.  And by no means am I anywhere near you all's level.

1)What changed since December.  To my recollection Dec was still the legacy video player.  That's a reason I though MOV files wouldn't play.  After Dec was VLC  which should natively just work for all video.  Correct me if I'm wrong here.

2)A quick google on raspberry-pi 2 and GPU memory
They talk about how configurable the memory can be on older models but the Pi4 assigns memory dynamically.

Just to share, not sure any of this will help
https://raspberrypi.stackexchange.com/questions/27468/raspberry-pi-2-1024m-increase-gpu-memory-to-512-at-least
https://forums.raspberrypi.com/viewtopic.php?t=336587

Random food for thought:
3)Is Dynaframe actually doing anything special for encode/decode of videos that VLC won't just handle for you?  
3.A)For the VLC player are you using alloc and malloc or dotnet core objects?  As I remember dotnet in general a stream is unmanaged and you have to dispose of the stream yourself.
3.B)How are you holding on to the video object?  As a static instance or creating a new one each video when it plays?
3.C)Does VLC provide best practices for how to handle these objects?  Meaning if they just give an example they may have not considered the garbage collection ramification in that example

4)Is the video portion of your code unit testable so you can put it under load and see how the memory behaves?  Also so once we get this fixed we prevent regression.


Update:  I'm at 1.5 days of uptime with the logging set to info.  Still waiting for it to crash.  Once I get those logs I'll try both of those ideas.  Creating a playlist of just images and just videos.  For the video test, I'll throw all the videos I have at it which should exacerbate the issue and give a faster turnaround time for testing, I hope.

**Comment by Geektoolkit** [comment]
Those are great suggestions! And your 2 cents is worth much more than 2 cents, we value the help and ideas, and appreciate them :)

We've actually been on VLC for quite a while, possibly a year now.  We use an Avalonia wrapper around VLC sharp in it's own window.  When we say we 'rewrite the video engine' it's more of when and how videos are played.  I want to make sure it's videos first  before digging in more here, but the VLC player we use is managed.  The rewrite in the engine was to actually move away from other memory leaks we were seeing in video due to not using it the way it was recommended, and to tighten up the code on how and when we called it.  I'd be very surprised if this ends up being VLC due to that change as we've seen much better memory and performance since doing it.  HOWEVER....I believe we may have rev'd the version we used...and that can always introduce other issues.

The major changes we're currently looking into is around 'windows' which we manage.  When I added the overlay code, it created an invisible window that is there whether we show an overlay or not. If it's not shown it's hidden, but the object is still there.  The infobar is another window, and bdlou reported that we may have some issues there.  So there's quite a bit of stuff we're looking into. 

I have tests going to see if the overlay window is causing any issues on pi4 as we are trying to get that rock solid, and another test going for video.  I have one rock solid frame and one that isn't, so trying to narrow down if that's it myself.  But these are pi4's so they take longer to show issues.  The hard part is a simple memory view isn't really showing me what I'd expect to see for a memory leak which would be a 'stair step' effect as the deallocation fails (or garbage collection in managed code). 

We'll keep digging in.

**Comment by jcrowegitHu8** [comment]
I'm at 3 days of up time. I believe that turning logging on changes the code path that is causing the issue.

Can you search your code for conditional logic that is outside your Logger class that would be impacting out of memory.  Meaning with logging on you probably instantiate objects differently is my guess to enrich the log info.

I'm going to turn logging off and do a list of all videos to see if I can crash it quicker.

Correction: we didn't get the out of memory but the system seems unresponsive.  Logs show a lack of activity.

[dynaframe-2023-05-17-16-22.log](https://github.com/Geektoolkit/DynaframeProIssues/files/11524399/dynaframe-2023-05-17-16-22.log)

**Comment by jcrowegitHu8** [comment]
Great News!  I believe I have confirmed my suspicions.

How to reproduce:
1)Create a playlist of all videos.  Try to max out as much as you can.  Ideally all good videos that you know to have worked in smaller playlist.
2)Turn off logging.  This is critical!  If logging is on.  The system doesn't seem to crash but does seem to stop playing videos as some point.
3) Out of memory in about 1 hour.

Here is the log from the all video playlist.
[dynaframe-2023-05-21-06-23.zip](https://github.com/Geektoolkit/DynaframeProIssues/files/11525745/dynaframe-2023-05-21-06-23.zip)

Here is the playlist. (21 items 604MB)
![image](https://github.com/Geektoolkit/DynaframeProIssues/assets/17546577/cc062f19-af3c-48d4-8319-4b12cabdc961)

Feedback:
1) I really wish all log messages had a time stamp as I'm having to deduce the time of crash from my own telemetry so your mileage may vary.

**Comment by bdlou** [comment]
In older images, we had gpu_mem set to 256 for all devices.  This would cause some of the older Pi devices to not boot at all.  So we moved the line specifically to [pi4].  So if you've clean imaged with the releases after December, you're using the default gpu_mem, which I believe is 64.  Please try the following:

ssh into your device
sudo nano /boot/config.txt
Scroll to the bottom and add a [pi2] section
Underneath that add the following line:
gpu_mem=256
Hit Ctrl + X, save the change, then sudo reboot.

I'm not saying that your logging theory is impossible, but we only check the setting in two places.  One to determine what HTML to display to the log page in our web UI, and the other when we call our internal logger, and the first line is to check if the setting is off, and return if it is, so we do nothing.

The only lines that don't have timestamps are the ones that are coming directly from linux, external to Dynaframe code.  If you know of a way to get those to be timestamped, let us know!

**Comment by qwksilver** [comment]
I want to clarify here and give you one option to improve logging.

Clarity, the store code also likely updated you to pi4 mode only on gpu memory, only a very few machines that had customization in config.txt would have been skipped.  I will also confirm that all that logging is from Linux writing out to the active background console and echoed into our logging.

small patch to logging even with logging off in the web ui.
```sudo nano /home/pi/Dynaframe/.config/dynaframe.sh```

if you update the last few lines to be as follows, it will give you the date and time right after your out of memory notice from linux.  if you want to delve that deep and it seems you have those skills from the conversation above.

```
logfooter=$(date +"%m/%d/%Y %H:%M:%S:Exit")
echo $logfooter
echo -e "\n\ndynaframe.sh we are done with this window you may now hit enter to continue"
exit
```

**Comment by jcrowegitHu8** [comment]
I just wanted to clarify a few things so I understand the paths forward from the team.  You all have been great at chiming in and educating/helping.

At Team
1)I believe we have identified that the issue is indeed a memory leak with the video portion of Dynaframe, correct?
1.A) If 1 is correct then there is no need for me to test a list of all images.  Do you all agree?
1.B) Are you all able to reproduce the issue on your own internal hardware (pi4) with just more videos? 

**Summary** for 1 is I want to make sure I have given you enough info that the team can reasonable reproduce the issue.

@bdlou Just to clarify the goal of your recommendation:

> ssh into your device
sudo nano /boot/config.txt
Scroll to the bottom and add a [pi2] section
Underneath that add the following line:
gpu_mem=256
Hit Ctrl + X, save the change, then sudo reboot.

2) You recommendation of increasing the gpu_mem=256 is just a temporary work around, while you all continue to try and find /resolve the issue?

2.A) I believe I would have clean imaged to the December release.  My config.txt does have the [pi4] section so I believe the auto update from the store should have my system up to date.

@qwksilver 

Thanks for your recommendation.  I'll use that to continue to help testing with this issue further and to be more accurate in the information I provide.

> logfooter=$(date +"%m/%d/%Y %H:%M:%S:Exit")
echo $logfooter
echo -e "\n\ndynaframe.sh we are done with this window you may now hit enter to continue"
exit

**Comment by bdlou** [comment]
@jcrowegitHu8 No, we have not identified a memory leak in video playback.

The gpu_mem is not a temporary workaround.  It is a minimum requirement.  The change is needed to return to parity with older releases on your Raspberry Pi model, the Pi 2.

I believe your system is running with 64mb of gpu memory at defaults.  On the Pi2 I have, our intro video only plays green with this default.  Changing to 256 addresses that.

Please make that change, and let us know if you see the same behavior.

**Comment by Geektoolkit** [comment]
Re: 1 - We suspect videos, and we're going down that path, but we don't know for sure it's videos yet. There's a lot of things that can cause memory issues in this system, and videos could do something to exacerbate it, or it could be that videos are THE thing that cause it. We have to keep investigating and make absolutely sure.  We've had some bugs in the past that we thought were one thing, but turned out to be something very different, so I'm very patient on getting the right data before we attack something. The biggest time wastes we've had was chasing a symptom and not a solution.

Re: 1B - are you able to repro on a pi4

The team doesn't have a solid repro yet on  pi4s.  I'd like you to still run the image only please so that we can have the negative data...if that does crash then it tells us very very important info that this may not be video related but engine related.  If it doesn't then that puts a laser focus on video.  but until we know that , assuming video isn't a safe bet. Esp. given that you're seeing different results with logging on/off. I'd like to know that matrix:
Videos only, logging on
Videos only, logging off
Images only, logging on
Images only, logging off

I'm running tests in parallel with you to try to repro on a pi4. I thought I had it, but turns out that a corrupt video file was taking the system down.  So removing that and will be running tests today to try to repro.

**Comment by Geektoolkit** [comment]
Ok we have a solid repro on pi4 and are investigating.  The 'whorlds' videos from the store, setup as a dedicated playlist will repro this on a pi4 in about 2-4 hours with a 10 second transition time ( play full video set to off).

The log looks the same as what you shared.  I don't repro with images even after 3 days.  
Overlays were off (though technically the window is still there, just hidden)
I have repros with logging on and off
I have repros with video memory set to 256 and 512gigs (though it does seem to take longer with higher video memory)
Frame sync was off
Playlist was only videos. 

Log shows VLC trying to allocate memory and failing over and over until eventually the system goes down.  Next steps are for the team to get a debug log with some additional telemetry in the logs to try to see where the leaks happening.

@jcrowegitHu8  Thankyou for reporting this. Took us a bit to get the data. I suspect you're seeing it MUCH earlier because of a pi2 with a mixed playlist, but we have the data now to repro it so we will work on figuring it out and fixing it.

**Comment by jcrowegitHu8** [comment]
Hi @Geektoolkit, I wasn't sure if the fix for this is meant to be in this June release or not.  Can you please confirm?  Thank you.

https://www.patreon.com/posts/july-release-is-85243379

**Comment by Geektoolkit** [comment]
Please let me know the frame rate of the videos that are failing. If they aren't 30 please try them at 30

**Comment by jcrowegitHu8** [comment]
Hi, the video's are 30 frames/second.  I'm not sure why some show <30.  Regardless, I still get the same out of memory error.

```
06/28/2023 12:12:10:Startup
Out of memory.
06/28/2023 14:12:12:Exit
```
1)Can you please share what you have learned around why frame rate matters for out of memory exceptions?
2)What are next steps?

![image](https://github.com/Geektoolkit/DynaframeProIssues/assets/17546577/4661dcac-71c8-4cad-813b-50908e94f6d0)

**Comment by jcrowegitHu8** [comment]
Bumping this to see if it's still being worked on as the ability to play videos is the main feature for me.  There are many other solutions to show just pictures.

**Comment by bdlou** [comment]
I am actively developing a way to no longer attempt to play videos that exceed the capabilities of playback on a Raspberry Pi, as well as other scenarios where we have seen a video bring down the entire system.  We hope to have a beta available soon.

**Comment by Geektoolkit** [comment]
Lou got this into Beta and it'll be in the next release.  We'll enable ways to toggle the filters after that for advanced users. He also did some other work to help with stability.  We'll continue to do what we can as we figure out things here to improve video stabilaty.

Regarding why frame rate matters - We had 60fps videos taking down VLC in about 2 hours (stress scenario, 5 second transitions).  Simply using ffmpeg to convert them to 30fps increased stabilty to over 2 weeks, but then we hit a different segfault/stack.  The fix that went into beta is meant to help address that and further increase stability.  

The change Lou made also filters out codecds that are problematic to pis.  In short, we're working on it, and a new release will be out soon that hopefully addresses this.  One thing though, I'd keep logging off on the pi2 simply to preserve as much memory as possible.   When logging is enabled the log is kept in memory, and then the pi is also opening up a potentially large file and writing to it.   In addition, logging puts a bit of stress on the machien as it starts to listen to a number of debug signals (memory usage, disk usage, etc) that get turned off when logging is off.  So please do testing for stability with it off, and then if we hit something we'll turn it on to try to catch what we can.

**Comment by Geektoolkit** [comment]
I'm going through bugs and this has been shipped by Lou along with a followup feature set to turn things on/off.  Closing this out unless we still have repros of this in the recent builds.
