### ISSUE TITLE
Overlays - Windows XP Title not selectable

### ISSUE THREAD

**Issue by ajw2060** [Geektoolkit/DynaframeProIssues#56]
This is observed in build 620dbec.

The EXIF tag "Windows XP Title" does not seem to exist in the dropdown list of available EXIF tags to configure in the overlay.  The Windows XP Title was mapped to the "Title" field in a previous release.  The "Title" field now maps to the EXIF "ImageDescription".  The only way to get the Windows XP Title seems to be to explicitly specify "Windows XP Title" in the "EXIF Tag (Advanced)" text box.  Can we have the "Windows XP Title" and perhaps the other couple "Windows XP ..." tags available in the dropdown list.  Please name them the same as their EXIF descriptions so they are obvious.  The current mapping of fields such as "Title" to "ImageDescription" makes it a trial and error process to select the actual EXIF tag needed.

**Comment by Geektoolkit** [comment]
I'm sorry I broke this, I see where this was removed when I did the update, and have fixed it in our private branch with a goal of releasing in November. I've also added in parens the 'actual' names of exif tags if the friendly name I chose didn't match so that it removes guessing.

  <option value="Windows XP Title">Title (Windows XP Title)</option>
  <option value="Windows XP Author">Author (Windows XP Author)</option>
  <option value="Windows XP Subject">Subject (Windows XP Subject)</option>
  <option value="Windows XP Keywords">Keywords (Windows XP Keywords)</option> 
  
  This should be in the next release.
